#!/bin/sh

# General shortcuts
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rmd="sudo rm -r" \
	ls="exa" \
	l="exa" \
	lb="lsblk" \
	cl="clear" \
	t="touch" \
	a="c .." \
  z="zathura" \
	g="git" \
	gk="gpg --list-keys --keyid-format long" \
  kt="v ~/.config/kitty/theme.conf" \
  xm="v ~/.xmonad/xmonad.hs" \
	bh="v ~/.bash_history" \
  dc="c ~/Documents" \
  dw="c ~/Downloads" \
  nf="neofetch" \
	ts="ts-node" \
	p="sudo pacman" \
	update="sudo pacman -Syu --noconfirm; xmonad --recompile" \
	uppass="sender .password-store" \
	brpass="getter .password-store" \
	clean="p -Qtdp; p -Scc; sudo rm -rf .cache" \
	empty="sudo rm ~/.cache/vim/swap/*" \
	sdn="sudo shutdown now" \
	rb="sudo reboot" \
	ka="killall" \
	r="ranger" \
	see="ncdu"\
	v="vim" \
	tree="lsd --tree"\
	vm="vim src/main.rs" \
	vl="vim src/lib.rs" \
	vi="vim index.tsx" \
	vp="vim ./+page.svelte" \


base(){
	pwd | cut -d'/' -f1-4
}

b(){
	c $(base)
}

c(){
  cd $1
	export FOLDER=$(base)
}

mkd(){
	mkdir -p $1
	c $1
}

s(){
	c "$(base)/src"
}

# Python shortcuts
alias \
	pye="source ~/Documents/venvs/maths/bin/activate" \

# server shortcut
alias \
	server="ssh root@104.156.231.83" \

# rust shortcuts
alias \
	cr="cargo build --release" \
	ca="cargo add" \

ta(){
	c "$(base)/target/release"
}

# docker shortcuts
alias \
	dk="sudo docker" \
	dkc="sudo docker ps -a" \
	dkei="sudo docker exec -it" \
	dki="sudo docker images" \
	dcc="sudo docker-compose" \
	rdcc="sudo docker-compose up --build -d" \
	dre="sudo docker system prune -a" \
	dvp="sudo docker volume prune" \


dri(){
	instances=$(docker image ls -q)
	dk rmi $instances
}

drc(){
	instance=$(docker ps -a -q &)
	dk stop $instances
	dk rm $instances
}


# pnpm shortcuts svelte
alias \
	dev="pnpm run dev --host" \
	build="pnpm run build" \

co(){
	c "$(base)/src/components"
}

ro(){
	c "$(base)/src/routes"
}

li(){
	c "$(base)/src/lib"
}

bk(){
	c "$(base)/backend"
}


# ssh with vps
getter(){
	rsync -avz root@104.156.231.83:/var/www/server/static/files/$1 .
}

sender(){
	rsync -urvP $1 root@104.156.231.83:/var/www/server/static/files/$2
}

sender_binary(){
	rsync -urvP $1 root@104.156.231.83:/var/www/server/static/bins/$2
}


# video editing shortcuts
convert(){
	target=$1
	output=$2
	$(ffmpeg -i $target -vf yadif -codec:v libx264 -crf 30 -bf 2 -flags +cgop -pix_fmt yuv420p -codec:a aac -strict -2 -b:a 384k -r:a 48000 $output.mp4)
}

mixer(){
	video=$1
	sound=$2
	name=$3
	$(ffmpeg -i $video -i $sound -c:v copy -c:a copy $name.mkv)
}

mt(){
	target=$1
	sudo mount "/dev/$target" /mnt/simple
}

um(){
	sync
	sudo umount /mnt/simple
}

tarit(){
	name=$1
	optional=$2
	if [ -z "$optional" ]; then
		tar -cf - "$name" | pigz > "$name.tar.gz"
	else
		tar -cf - "$name" | pigz > "$optional.tar.gz"
	fi
}

untarit(){
	target=$1
	tar -I pigz -xf "$target"
}
