# bashrc

# Enables changing to a directory by simply typing its name.
shopt -s autocd

# Exit if the script is not running in an interactive shell to
# prevent unwanted behavior.
[[ $- != *i* ]] && return

# Set shell history to unlimited for both current session and history file
HISTSIZE=     # Unlimited history in current session
HISTFILESIZE= # Unlimited history in history file

# Prevent duplicate commands in history:
# ignore consecutive duplicates and remove previous entries
HISTCONTROL=ignoredups:erasedups

# Set Vim as the default text editor
export EDITOR=vim

# Set Qutebroweser as the default browser
export BROWSER=qutebrowser

# Set common variables
export DC="$HOME/Documents"
export DW="$HOME/Downloads"
export CFG="$HOME/.config"
export DT="$HOME/.dotfiles"
export BN="$HOME/.binaries"

# Enable appending to the history file on shell exit,
# preserving previous sessions' history
shopt -s histappend

# Update command history after each command: append to
# the history file, clear the current history, and reload from the file
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"

# Prevent entering power-saving mode
xset dpms 0 0 0

# Enable Vim key bindings for command line editing in the terminal
set -o vi

# Load custom keyboard remappings and shell aliases for the current session
source ~/.aliasrc
source ~/.keyboard

# Bash prompt name
PS1='🦀🚀🛸\w\[$(tput sgr0)\]> '

# Add custom binary directories to the PATH for easy execution
export PATH="$PATH:$HOME/.binaries"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.local/bin"
