[manager]
ratio = [2, 5, 3]

[opener]
edit = [
	{ run = 'vim "$@"', block = true },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
reveal = [
	{ run = 'sxiv "$@"', desc = "Open images"}
]
pdf = [
	{ run = 'zathura "$@"', desc = "Open pdfs"}
]


[open]
rules = [
    { mime = "text/*", use = "edit" },
    { mime = "video/*", use = "play" },
    { mime = "image/*", use = "reveal" },

    { name = "*.jpg", use = "reveal" },
    { name = "*.{json,js,ts,tsx,jsx}", use = "edit" },
    { name = "*.pdf", use = "pdf" },
    { name = "*.epub", use = "pdf" },
    { name = "*.{mp3,wav}", use = "play" },
]
