#!/bin/sh

sveltec(){
	directory=$1
	mkdir $directory
  capitalized=$(remove_hyphen_and_capitalize $directory)
  echo "export { default as $capitalized } from './$directory/$directory.svelte';" >> "index.ts"

	echo "<script lang=\"ts\">
</script>
	" > "$directory/$directory.svelte"
}

svelter(){
	directory=$1
	mkdir -p $directory

	echo "<script lang=\"ts\">
</script>
	" > "$directory/+page.svelte"
}


remove_hyphen_and_capitalize() {
  input=$1
  IFS="-" read -ra words <<< "$input"

  output=()
  for word in "${words[@]}"; do
    output+="${word^}"
  done

  echo $output
}
