#!/bin/sh

uppass-disk(){
  address=$1

  if [ $# -eq 0 ]; then
      echo "address required!"
      exit 1
  fi

  sudo cryptsetup open "/dev/$address" corge
  sudo mount "/dev/mapper/corge" "/mnt/encrypted"
  sudo rsync -urvP "$HOME/.password-store/" "/mnt/encrypted/passwords/password-store/"
  sudo umount "/mnt/encrypted"
  sudo cryptsetup close corge
}
