#!/bin/env bash

add_path_alias() {
# TODO
# Is it a react project
# Is the current dir the root dir
# Is sed available
# Has those files change in last vesion ( a ref is required )
# What if this command was already ran

# Add alias to tsconfig.app.json
paths="\\
    /* Custom paths */\\
    \"paths\": {\\
      \"@/*\": [\"./*\"]\\
     },
"
sed -i "/skipLib/a\ ${paths}" tsconfig.app.json

echo "File tsconfig.app.json modified."

# Add imports to vite.config.ts
imports="import type { AliasOptions } from \"vite\"\\
//@ts-ignore\\
import path from \"path\"\\
\\
//@ts-ignore\\
const root = path.resolve(__dirname, \".\");
"
sed -i "2 a\\${imports}" vite.config.ts


# Add configuration to vite.config.ts
resolve=" resolve: {\\
    alias: {\\
      \"@\": root,\\
    } as AliasOptions,\\
  },"
sed -i "/plugins/a\ ${resolve}" vite.config.ts

echo "File vite.config.ts modified."
}

create_vite() {
  # Removes the first argument which is "vite".
  shift
  # Default template is react-swc-ts
  { [ -n "$1" ] &&
    printf "\nCreaing scaffold with default template react-swc-ts..." &&
    bun create vite --template react-swc-ts "$1"; } || bun create vite "$@"
}

create_next() {
  # Removes the first argument which is "next".
  shift

  { [ -n "$1" ] &&
    printf "\nCreaing Next.js scaffold ..." &&
    bunx create-next-app@latest "$1"\
      --no-eslint\
      --no-src-dir\
      --no-import-alias\
      --typescript\
      --tailwind\
      --app; } ||
    bunx create-next-app@latest "$@"
}


biome_config() {
  echo "{
  \"formatter\": {
    \"lineWidth\": 60
  }
}" > biome.json

  echo "File biome.json created."
}


# This script is in construction, handling possible
# errors and other things.
# Lot of work still required

case $1 in
  init       )  create_vite "$@" ;;
  next       )  create_next "$@" ;;
  add        )  bun add "$@" ;;
  dev        )  bun run dev ;;
  build      )  bun run build ;;
  preview    )  bun run preview ;;
  start      )  bun run start ;;
  install    )  bun install ;;
  i          )  bun install ;;

  path-alias )  add_path_alias ;;
  biome      )  biome_config ;;
  *          )  cat << EOF
rx: react, A streamlined utility for quickly setting up web projects,
specifically with the React library:

  BUN COMMANDS:
    init           Creates a new Vite app.
    next           Initiates a new NextJS.
    add            Adds a package.
    dev            Initiates development server.
    build          Build current project.
    start          Initiates production server - NextJS.
    preview        Initiates production server - React.
    install(i)     Install dependencies.

  SCRIPTS:
    path-alias     Sets "@" alias for the project's root directory.
    biome          Adds a biome file configuration.

NOTE: This cli-tool still requires a lot of work.
EOF
esac
